window.ATELIER_TEMPLATES = [
  {
    id: 'sql-select', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Lire des données avec SELECT', priority: 'essential',
    description: 'Afficher uniquement les colonnes nécessaires d’une table.',
    syntax: 'SELECT colonne1, colonne2\nFROM nom_table;',
    example: 'SELECT Nom, Prenom\nFROM CLIENT;',
    remember: ['SELECT nomme les résultats à afficher.', 'FROM indique la table source.'],
    pitfalls: ['SELECT * fonctionne, mais expliciter les colonnes rend la réponse plus claire.'],
    exercise: 'Lister les noms et prénoms des clients ou étudiants.', tags: ['select', 'sql', 'lecture', 'colonnes'],
    examIds: ['special-monday-sql', 'special-tuesday-sql', 'special-wednesday-sql', 'silthu-sql-5', 'silwed-sql-5']
  },
  {
    id: 'sql-where', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Filtrer avec WHERE', priority: 'essential',
    description: 'Ne garder que les lignes qui satisfont une condition.',
    syntax: 'SELECT colonnes\nFROM table\nWHERE condition;',
    example: "SELECT Designation, Prix\nFROM PRODUIT\nWHERE Prix > 50000;",
    remember: ['WHERE filtre les lignes avant un regroupement.', 'Combine les critères avec AND / OR.'],
    pitfalls: ['Les textes s’écrivent entre apostrophes.', 'Pour NULL, utiliser IS NULL, pas = NULL.'],
    exercise: 'Trouver les clients d’une ville ou les produits au-dessus d’un prix.', tags: ['sql', 'where', 'filtre', 'condition'],
    examIds: ['special-tuesday-sql', 'special-wednesday-sql', 'silthu-sql-5', 'silwed-sql-5']
  },
  {
    id: 'sql-join-inner', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Relier des tables avec INNER JOIN', priority: 'essential',
    description: 'Assembler uniquement les lignes qui ont une correspondance dans les deux tables.',
    syntax: 'SELECT a.colonne, b.colonne\nFROM table_a a\nINNER JOIN table_b b ON b.cle = a.cle;',
    example: 'SELECT c.Nom, c.Prenom, f.Libelle\nFROM ETUDIANT c\nJOIN INSCRIPTION i ON i.IdEtudiant = c.IdEtudiant\nJOIN FORMATION f ON f.IdFormation = i.IdFormation;',
    remember: ['Chaque JOIN a une condition ON reliant les clés.', 'JOIN seul signifie généralement INNER JOIN.'],
    pitfalls: ['Une jointure incomplète peut multiplier les lignes ou relier les mauvaises données.'],
    exercise: 'Afficher étudiant, formation et date d’inscription.', tags: ['sql', 'join', 'inner join', 'jointure', 'clé étrangère'],
    examIds: ['special-monday-sql', 'special-tuesday-sql', 'special-wednesday-sql', 'silthu-sql-5', 'silwed-sql-5']
  },
  {
    id: 'sql-join-left', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Conserver toutes les lignes avec LEFT JOIN', priority: 'essential',
    description: 'Garder toutes les lignes de gauche, même sans correspondance à droite.',
    syntax: 'SELECT a.colonne, b.colonne\nFROM table_a a\nLEFT JOIN table_b b ON b.cle = a.cle;',
    example: 'SELECT f.Libelle, COUNT(i.IdInscription) AS effectif\nFROM FORMATION f\nLEFT JOIN INSCRIPTION i ON i.IdFormation = f.IdFormation\nGROUP BY f.IdFormation, f.Libelle;',
    remember: ['Les lignes sans correspondance reçoivent NULL côté droit.', 'COUNT(cle_droite) donne 0 pour une ligne sans correspondance.'],
    pitfalls: ['COUNT(*) compterait aussi la ligne conservée par LEFT JOIN ; compter une clé non NULL de la table jointe.'],
    exercise: 'Afficher toutes les formations, même celles sans inscrit.', tags: ['sql', 'left join', 'jointure', 'null', 'zéro'],
    examIds: ['special-monday-sql', 'special-wednesday-sql', 'silwed-sql-5']
  },
  {
    id: 'sql-group-count', language: 'SQL', category: 'Base de données', type: 'Agrégat',
    title: 'Compter par groupe avec GROUP BY', priority: 'essential',
    description: 'Compter les lignes de chaque catégorie, client ou formation.',
    syntax: 'SELECT colonne_groupe, COUNT(*) AS total\nFROM table\nGROUP BY colonne_groupe;',
    example: 'SELECT IdClient, COUNT(*) AS nb_commandes\nFROM COMMANDE\nGROUP BY IdClient;',
    remember: ['COUNT(*) compte les lignes.', 'Chaque colonne du SELECT non agrégée doit normalement être dans GROUP BY.'],
    pitfalls: ['Pour conserver les groupes sans ligne liée, partir de la table complète et utiliser LEFT JOIN.'],
    exercise: 'Compter les commandes de chaque client ou les livres de chaque catégorie.', tags: ['sql', 'group by', 'count', 'comptage', 'groupe'],
    examIds: ['special-monday-sql', 'special-tuesday-sql', 'special-wednesday-sql', 'silthu-sql-1', 'silthu-sql-4', 'silthu-sql-5', 'silwed-sql-4', 'silwed-sql-5']
  },
  {
    id: 'sql-having', language: 'SQL', category: 'Base de données', type: 'Agrégat',
    title: 'Filtrer les groupes avec HAVING', priority: 'essential',
    description: 'Garder les groupes après le calcul de COUNT, SUM ou AVG.',
    syntax: 'SELECT colonne_groupe, COUNT(*) AS total\nFROM table\nGROUP BY colonne_groupe\nHAVING COUNT(*) > valeur;',
    example: 'SELECT IdClient, COUNT(*) AS nb_commandes\nFROM COMMANDE\nGROUP BY IdClient\nHAVING COUNT(*) >= 2;',
    remember: ['WHERE filtre les lignes AVANT GROUP BY.', 'HAVING filtre les groupes APRÈS GROUP BY.'],
    pitfalls: ['Ne pas mettre une condition sur un agrégat dans WHERE.'],
    exercise: 'Afficher les clients ayant effectué au moins deux commandes.', tags: ['sql', 'having', 'where', 'group by', 'count', 'filtre'],
    examIds: ['special-tuesday-sql', 'silthu-sql-1', 'silthu-sql-4', 'silwed-sql-1']
  },
  {
    id: 'sql-sum-avg-min-max', language: 'SQL', category: 'Base de données', type: 'Agrégat',
    title: 'Calculer SUM, AVG, MIN et MAX', priority: 'frequent',
    description: 'Résumer les nombres d’un ensemble ou d’un groupe.',
    syntax: 'SELECT SUM(montant), AVG(montant), MIN(montant), MAX(montant)\nFROM table;',
    example: 'SELECT IdReservation, SUM(Montant) AS total_paye\nFROM PAIEMENT\nGROUP BY IdReservation;',
    remember: ['SUM additionne ; AVG calcule la moyenne.', 'MIN et MAX donnent les bornes.'],
    pitfalls: ['Les fonctions d’agrégat ignorent les valeurs NULL, sauf COUNT(*), qui compte les lignes.'],
    exercise: 'Calculer le total des paiements par réservation ou le tarif total par médecin.', tags: ['sql', 'sum', 'avg', 'min', 'max', 'agrégat'],
    examIds: ['special-wednesday-sql', 'silthu-sql-1', 'silthu-sql-5']
  },
  {
    id: 'sql-between-null', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Tester une plage ou une valeur absente', priority: 'frequent',
    description: 'Utiliser BETWEEN pour une plage inclusive, et IS NULL pour une donnée absente.',
    syntax: 'WHERE valeur BETWEEN borne_min AND borne_max\nWHERE colonne IS NULL\nWHERE colonne IS NOT NULL',
    example: "SELECT Numero, PrixNuit\nFROM CHAMBRE\nWHERE PrixNuit BETWEEN 30000 AND 75000;\n\nSELECT IdReservation\nFROM RESERVATION\nWHERE DateRetour IS NULL;",
    remember: ['BETWEEN inclut ses deux bornes.', 'NULL signifie valeur inconnue/absente.'],
    pitfalls: ['Ne pas écrire colonne = NULL ; écrire IS NULL ou IS NOT NULL.'],
    exercise: 'Filtrer une plage de prix ou rechercher les emprunts non retournés.', tags: ['sql', 'between', 'null', 'is null', 'is not null', 'plage'],
    examIds: ['special-wednesday-sql', 'silwed-sql-5']
  },
  {
    id: 'sql-order-distinct', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Trier et supprimer les doublons', priority: 'frequent',
    description: 'ORDER BY trie le résultat ; DISTINCT ne garde qu’une occurrence de chaque résultat.',
    syntax: 'SELECT DISTINCT colonne\nFROM table\nORDER BY colonne ASC;',
    example: 'SELECT DISTINCT Ville\nFROM CLIENT\nORDER BY Ville ASC;',
    remember: ['ASC est l’ordre croissant ; DESC est décroissant.', 'ORDER BY se place à la fin de la requête.'],
    pitfalls: ['DISTINCT s’applique à la combinaison des colonnes sélectionnées.'],
    exercise: 'Afficher les villes une seule fois et les trier.', tags: ['sql', 'order by', 'distinct', 'tri'],
    examIds: ['silthu-sql-4', 'silwed-sql-4']
  },
  {
    id: 'sql-keys-create', language: 'SQL', category: 'Base de données', type: 'Contrainte',
    title: 'Déclarer clés primaires et étrangères', priority: 'essential',
    description: 'Une clé primaire identifie une ligne ; une clé étrangère relie une table à une autre.',
    syntax: 'CREATE TABLE enfant (\n  id INT PRIMARY KEY,\n  parent_id INT NOT NULL,\n  FOREIGN KEY (parent_id) REFERENCES parent(id)\n);',
    example: 'CREATE TABLE INSCRIPTION (\n  IdInscription INT PRIMARY KEY,\n  DateInscription DATE NOT NULL,\n  IdEtudiant INT NOT NULL,\n  IdFormation INT NOT NULL,\n  FOREIGN KEY (IdEtudiant) REFERENCES ETUDIANT(IdEtudiant),\n  FOREIGN KEY (IdFormation) REFERENCES FORMATION(IdFormation)\n);',
    remember: ['Créer les tables parentes avant la table enfant.', 'Une clé primaire est unique et non NULL.', 'Une FK doit référencer une valeur existante, ou NULL si autorisé.'],
    pitfalls: ['Ne pas confondre une clé étrangère avec une clé primaire : une FK peut se répéter.'],
    exercise: 'Définir CLIENT, COMMANDE et les liens entre leurs identifiants.', tags: ['sql', 'create table', 'primary key', 'foreign key', 'clé primaire', 'clé étrangère'],
    examIds: ['special-monday-sql', 'special-tuesday-sql', 'special-wednesday-sql', 'silwed-sql-1', 'silwed-sql-2', 'silwed-sql-3']
  },
  {
    id: 'sql-constraints', language: 'SQL', category: 'Base de données', type: 'Contrainte',
    title: 'Choisir les contraintes d’une colonne', priority: 'frequent',
    description: 'Déclarer les règles qui protègent les données de la table.',
    syntax: 'colonne TYPE NOT NULL UNIQUE DEFAULT valeur\nCHECK (condition)',
    example: "Email VARCHAR(150) NOT NULL UNIQUE,\nEtat VARCHAR(20) NOT NULL DEFAULT 'Disponible',\nCHECK (Prix >= 0)",
    remember: ['NOT NULL interdit l’absence de valeur.', 'UNIQUE empêche les doublons.', 'DEFAULT fournit une valeur si rien n’est saisi.'],
    pitfalls: ['CHECK et le support de ses expressions varient légèrement selon le SGBD.'],
    exercise: 'Protéger email, état ou prix dans un schéma de bibliothèque/hôtel.', tags: ['sql', 'contrainte', 'not null', 'unique', 'default', 'check'],
    examIds: ['silwed-sql-1', 'silwed-sql-2']
  },
  {
    id: 'sql-insert', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Insérer une ligne avec INSERT', priority: 'complementary',
    description: 'Ajouter une nouvelle ligne en nommant les colonnes renseignées.',
    syntax: 'INSERT INTO nom_table (colonne1, colonne2)\nVALUES (valeur1, valeur2);',
    example: "INSERT INTO CATEGORIE (IdCategorie, Libelle)\nVALUES (1, 'Informatique');",
    remember: ['L’ordre des valeurs correspond à l’ordre des colonnes.', 'Respecter les clés étrangères avant d’ajouter la ligne enfant.'],
    pitfalls: ['Une chaîne s’écrit entre apostrophes ; ne jamais concaténer des entrées utilisateur dans du SQL.'],
    exercise: 'Ajouter d’abord un adhérent et un livre, puis leur emprunt.', tags: ['sql', 'insert', 'insert into', 'ajouter'],
    examIds: ['silwed-sql-1', 'silwed-sql-2']
  },
  {
    id: 'sql-update-delete', language: 'SQL', category: 'Base de données', type: 'Requête SQL',
    title: 'Modifier ou supprimer une ligne', priority: 'complementary',
    description: 'UPDATE modifie les lignes ciblées ; DELETE supprime les lignes ciblées.',
    syntax: 'UPDATE nom_table SET colonne = valeur WHERE condition;\nDELETE FROM nom_table WHERE condition;',
    example: "UPDATE CHAMBRE SET Etat = 'Occupée' WHERE IdChambre = 12;\nDELETE FROM RESERVATION WHERE IdReservation = 42;",
    remember: ['Vérifier la condition WHERE avant exécution.', 'Les contraintes de référence peuvent empêcher une suppression.'],
    pitfalls: ['Sans WHERE, toutes les lignes sont modifiées ou supprimées.'],
    exercise: 'Mettre à jour l’état d’une chambre ou supprimer une réservation autorisée.', tags: ['sql', 'update', 'delete', 'modifier', 'supprimer'],
    examIds: ['special-wednesday-sql', 'silwed-sql-2']
  },
  {
    id: 'java-class', language: 'Java', category: 'POO', type: 'Classe',
    title: 'Déclarer une classe', priority: 'essential',
    description: 'Définir le type d’objet, son état (attributs) et ses comportements (méthodes).',
    syntax: 'public class NomClasse {\n  private Type attribut;\n  public NomClasse(...) { ... }\n  public Type nomMethode(...) { ... }\n}',
    example: 'public class Chambre {\n  private String numero;\n  private double prixNuit;\n\n  public Chambre(String numero, double prixNuit) {\n    this.numero = numero;\n    this.prixNuit = prixNuit;\n  }\n}',
    remember: ['Le nom public de la classe correspond au nom du fichier.', 'Les attributs d’instance sont privés par défaut dans les modèles d’examen.'],
    pitfalls: ['La déclaration de classe ne se termine pas par un point-virgule.'],
    exercise: 'Créer Chambre, Employe, Produit ou CompteBancaire selon le sujet.', tags: ['java', 'classe', 'class', 'poo'],
    examIds: ['special-monday-java', 'special-tuesday-java', 'special-wednesday-java', 'silthu-java-5', 'silwed-java-5']
  },
  {
    id: 'java-attribute', language: 'Java', category: 'POO', type: 'Attribut',
    title: 'Déclarer un attribut', priority: 'essential',
    description: 'Mémoriser une donnée qui décrit l’état de chaque objet.',
    syntax: 'private Type nom;\nprivate Type autreNom;',
    example: 'private String matricule;\nprivate String nom;\nprivate double moyenne;\nprivate int quantiteStock;',
    remember: ['Écrire la visibilité, le type, le nom et le point-virgule.', 'Utiliser String pour le texte, int pour entier, double pour réel.'],
    pitfalls: ['Un champ d’instance ne doit pas être déclaré localement dans le constructeur.'],
    exercise: 'Déclarer matricule, nom, prénom et moyenne dans Etudiant.', tags: ['java', 'attribut', 'champ', 'variable', 'type'],
    examIds: ['special-monday-java', 'special-tuesday-java', 'special-wednesday-java', 'silwed-java-3']
  },
  {
    id: 'java-visibility', language: 'Java', category: 'POO', type: 'Visibilité',
    title: 'Choisir public, private ou protected', priority: 'essential',
    description: 'Contrôler où une classe, un champ ou une méthode peut être utilisé.',
    syntax: 'private Type etat;\npublic Type methode() { ... }\nprotected Type champHerite;',
    example: 'public class Employe {\n  private double salaire;\n\n  public double getSalaire() {\n    return salaire;\n  }\n}',
    remember: ['private : seulement dans la classe.', 'public : accessible depuis le code appelant.', 'protected : accessible dans le package et les sous-classes selon les règles Java.'],
    pitfalls: ['Ne pas rendre tous les attributs publics : l’encapsulation contrôle leur modification.'],
    exercise: 'Cacher solde ou salaire, puis les lire via un getter.', tags: ['java', 'public', 'private', 'protected', 'visibilité', 'encapsulation'],
    examIds: ['special-tuesday-java', 'special-wednesday-java', 'silwed-java-1']
  },
  {
    id: 'java-constructor', language: 'Java', category: 'POO', type: 'Constructeur',
    title: 'Écrire un constructeur', priority: 'essential',
    description: 'Initialiser les attributs au moment où l’objet est créé.',
    syntax: 'public NomClasse(Type parametre) {\n  this.attribut = parametre;\n}',
    example: 'public Etudiant(String matricule, String nom, double moyenne) {\n  this.matricule = matricule;\n  this.nom = nom;\n  this.moyenne = moyenne;\n}',
    remember: ['Le constructeur porte le nom de la classe.', 'Il n’a pas de type de retour, pas même void.', 'this désigne l’objet courant.'],
    pitfalls: ['Écrire public void Etudiant(...) crée une méthode, pas un constructeur.'],
    exercise: 'Initialiser les champs d’Etudiant, Chambre, Employe ou Produit.', tags: ['java', 'constructeur', 'constructor', 'this', 'poo'],
    examIds: ['special-monday-java', 'special-tuesday-java', 'special-wednesday-java', 'silthu-java-5', 'silwed-java-3']
  },
  {
    id: 'java-getter', language: 'Java', category: 'POO', type: 'Méthode',
    title: 'Écrire un getter', priority: 'essential',
    description: 'Renvoyer la valeur d’un attribut privé sans l’exposer directement.',
    syntax: 'public Type getNomAttribut() {\n  return nomAttribut;\n}',
    example: 'private String nom;\n\npublic String getNom() {\n  return nom;\n}',
    remember: ['Le type retourné correspond au type de l’attribut.', 'Un getter retourne une valeur.'],
    pitfalls: ['Ne pas écrire void si la méthode doit fournir la valeur.'],
    exercise: 'Écrire getSolde() pour CompteBancaire ou getSalaire() pour Employe.', tags: ['java', 'getter', 'get', 'méthode', 'accès'],
    examIds: ['special-tuesday-java', 'special-wednesday-java', 'silthu-java-3']
  },
  {
    id: 'java-setter', language: 'Java', category: 'POO', type: 'Méthode',
    title: 'Écrire un setter', priority: 'essential',
    description: 'Modifier un attribut privé, avec validation possible.',
    syntax: 'public void setNomAttribut(Type valeur) {\n  this.nomAttribut = valeur;\n}',
    example: 'private String nom;\n\npublic void setNom(String nom) {\n  this.nom = nom;\n}',
    remember: ['Un setter standard retourne void.', 'this.nom désigne le champ ; nom désigne le paramètre.'],
    pitfalls: ['Sans this, une affectation nom = nom ne modifie pas le champ.'],
    exercise: 'Écrire setSalaire ou setEtat en contrôlant les valeurs acceptées.', tags: ['java', 'setter', 'set', 'méthode', 'accès'],
    examIds: ['special-tuesday-java', 'special-wednesday-java']
  },
  {
    id: 'java-method', language: 'Java', category: 'POO', type: 'Méthode',
    title: 'Écrire une méthode', priority: 'essential',
    description: 'Décrire une action ; la signature précise visibilité, retour, nom et paramètres.',
    syntax: 'public TypeRetour nomMethode(Type parametre) {\n  // traitement\n  return resultat;\n}',
    example: 'public boolean admis() {\n  return moyenne >= 10;\n}\n\npublic double valeurStock() {\n  return prixUnitaire * quantite;\n}',
    remember: ['public/private : visibilité.', 'TypeRetour : valeur renvoyée, ou void si aucune.', 'Le nom est suivi de paramètres entre parenthèses ; le corps est entre accolades.'],
    pitfalls: ['Une méthode non-void doit retourner une valeur sur chaque chemin possible.'],
    exercise: 'Écrire admis(), estDisponible(), estEnRupture() ou calculerPrixSejour().', tags: ['java', 'méthode', 'retour', 'paramètre', 'void'],
    examIds: ['special-monday-java', 'special-tuesday-java', 'special-wednesday-java', 'silthu-java-3', 'silthu-java-5', 'silwed-java-5']
  },
  {
    id: 'java-object-call', language: 'Java', category: 'POO', type: 'Objet',
    title: 'Créer un objet et appeler une méthode', priority: 'essential',
    description: 'Instancier une classe avec new, puis utiliser son API avec le point.',
    syntax: 'NomClasse objet = new NomClasse(arguments);\nobjet.nomMethode();',
    example: 'Etudiant e = new Etudiant("E01", "Awa", 14.5);\ne.afficherInformations();\nif (e.admis()) {\n  System.out.println("Admis");\n}',
    remember: ['La variable a un type de classe.', 'new appelle un constructeur ; le point appelle un membre.'],
    pitfalls: ['Respecter exactement les paramètres définis dans le constructeur/méthode.'],
    exercise: 'Créer deux étudiants, employés ou chambres et afficher leurs résultats.', tags: ['java', 'objet', 'new', 'appel', 'instance'],
    examIds: ['special-monday-java', 'special-tuesday-java', 'special-wednesday-java', 'silthu-java-5', 'silwed-java-5']
  },
  {
    id: 'java-encapsulation', language: 'Java', category: 'POO', type: 'Classe',
    title: 'Appliquer l’encapsulation', priority: 'essential',
    description: 'Protéger l’état privé et fournir des méthodes d’accès contrôlées.',
    syntax: 'class Compte {\n  private double solde;\n  public double getSolde() { return solde; }\n  public void deposer(double montant) { ... }\n}',
    example: 'public void deposer(double montant) {\n  if (montant > 0) {\n    solde += montant;\n  }\n}',
    remember: ['Champs privés ; getters/setters ou méthodes métier publiques.', 'Valider une entrée avant de modifier l’état.'],
    pitfalls: ['Un setter aveugle peut contourner les règles métier ; préférer une méthode contrôlée si besoin.'],
    exercise: 'Protéger le solde bancaire, le stock d’un produit ou l’état d’une chambre.', tags: ['java', 'poo', 'encapsulation', 'private', 'getter', 'setter'],
    examIds: ['special-tuesday-java', 'special-wednesday-java', 'silthu-java-5', 'silwed-java-5']
  },
  {
    id: 'java-inheritance', language: 'Java', category: 'POO', type: 'Héritage',
    title: 'Hériter avec extends', priority: 'frequent',
    description: 'Spécialiser une classe en réutilisant son comportement.',
    syntax: 'public class Enfant extends Parent {\n  public Enfant(...) {\n    super(...);\n  }\n}',
    example: 'public class Suite extends Chambre {\n  private int capacite;\n\n  public Suite(String numero, double prix, int capacite) {\n    super(numero, prix);\n    this.capacite = capacite;\n  }\n}',
    remember: ['Java n’autorise qu’une seule classe mère directe.', 'super(...) appelle le constructeur parent.'],
    pitfalls: ['L’appel super(...) doit être la première instruction du constructeur enfant.'],
    exercise: 'Créer Suite à partir de Chambre ou Manager à partir de Employe.', tags: ['java', 'extends', 'héritage', 'super', 'poo'],
    examIds: ['special-tuesday-java', 'special-wednesday-java']
  },
  {
    id: 'java-interface', language: 'Java', category: 'POO', type: 'Interface',
    title: 'Déclarer et implémenter une interface', priority: 'complementary',
    description: 'Définir un contrat de méthodes qu’une classe s’engage à fournir.',
    syntax: 'interface Affichable {\n  void afficher();\n}\nclass Rapport implements Affichable {\n  public void afficher() { ... }\n}',
    example: 'interface Calculable {\n  double calculerTotal();\n}\nclass Facture implements Calculable {\n  public double calculerTotal() {\n    return montant;\n  }\n}',
    remember: ['Une classe utilise implements pour réaliser une interface.', 'Les méthodes abstraites d’interface sont publiques dans leur implémentation.'],
    pitfalls: ['extends sert à hériter d’une classe ; implements sert à implémenter une interface.'],
    exercise: 'À revoir comme distinction Java ; aucun exercice d’interface complet dans les sujets fournis.', tags: ['java', 'interface', 'implements', 'poo'],
    examIds: ['silwed-java-1']
  },
  {
    id: 'java-overload-override', language: 'Java', category: 'POO', type: 'Méthode',
    title: 'Distinguer surcharge et redéfinition', priority: 'frequent',
    description: 'La surcharge change les paramètres ; la redéfinition remplace un comportement hérité.',
    syntax: 'void afficher(String texte) { ... }\nvoid afficher(int nombre) { ... } // surcharge\n@Override\nvoid afficher() { ... } // redéfinition',
    example: 'class Employe {\n  public double calculerPrime() { return 0; }\n}\nclass Manager extends Employe {\n  @Override\n  public double calculerPrime() { return 50000; }\n}',
    remember: ['Surcharge : même nom, signatures différentes dans la classe.', 'Redéfinition : même signature dans une sous-classe.'],
    pitfalls: ['Changer seulement le type de retour ne suffit pas à surcharger.'],
    exercise: 'Comparer surcharge et redéfinition avec Employe et Manager.', tags: ['java', 'surcharge', 'overload', 'redéfinition', 'override'],
    examIds: ['special-tuesday-java', 'special-wednesday-java', 'silthu-java-2']
  },
  {
    id: 'java-array-max', language: 'Java', category: 'Autres', type: 'Boucle',
    title: 'Parcourir un tableau et trouver son maximum', priority: 'frequent',
    description: 'Initialiser le maximum au premier élément, puis comparer les suivants.',
    syntax: 'int max = valeurs[0];\nfor (int i = 1; i < valeurs.length; i++) {\n  if (valeurs[i] > max) max = valeurs[i];\n}',
    example: 'int[] notes = {12, 7, 16, 9};\nint max = notes[0];\nfor (int i = 1; i < notes.length; i++) {\n  if (notes[i] > max) max = notes[i];\n}\nSystem.out.println(max); // 16',
    remember: ['length est une propriété du tableau.', 'Commencer la boucle à 1 après avoir pris l’élément 0.'],
    pitfalls: ['Vérifier que le tableau n’est pas vide avant de lire valeurs[0].'],
    exercise: 'Expliquer la boucle qui trouve le maximum d’un tableau.', tags: ['java', 'tableau', 'boucle', 'maximum', 'for'],
    examIds: ['silthu-java-4']
  },
  {
    id: 'java-string-equals', language: 'Java', category: 'Autres', type: 'Comparaison',
    title: 'Comparer des chaînes Java', priority: 'frequent',
    description: 'Comparer le contenu de deux String avec equals.',
    syntax: 'chaine1.equals(chaine2)',
    example: 'if (etat.equals("Disponible")) {\n  return true;\n}\nreturn false;',
    remember: ['== compare les références d’objets.', 'equals compare le contenu des chaînes.'],
    pitfalls: ['Si la première chaîne peut être null, utiliser "Disponible".equals(etat).'],
    exercise: 'Tester si l’état d’une chambre est « Disponible ».', tags: ['java', 'string', 'equals', 'comparaison', '=='],
    examIds: ['special-wednesday-java', 'silthu-java-2']
  },
  {
    id: 'html-form', language: 'HTML', category: 'Formulaire', type: 'Formulaire',
    title: 'Créer un formulaire HTML', priority: 'frequent',
    description: 'Associer des champs nommés à une méthode d’envoi.',
    syntax: '<form method="POST" action="traitement.php">\n  <label for="nom">Nom</label>\n  <input id="nom" name="nom" type="text" required>\n  <button type="submit">Envoyer</button>\n</form>',
    example: '<form method="POST" action="connexion.php">\n  <label for="email">Courriel</label>\n  <input id="email" name="email" type="email" required>\n  <label for="motdepasse">Mot de passe</label>\n  <input id="motdepasse" name="motdepasse" type="password" required>\n  <button type="submit">Se connecter</button>\n</form>',
    remember: ['name donne la clé envoyée au serveur.', 'POST place les champs dans le corps HTTP ; HTTPS chiffre le transport.'],
    pitfalls: ['GET ne convient pas à un mot de passe.', 'POST n’est pas un chiffrement : utiliser HTTPS.'],
    exercise: 'Construire un formulaire d’inscription/connexion et justifier POST + HTTPS.', tags: ['html', 'form', 'formulaire', 'post', 'input', 'web'],
    examIds: ['wed-web-5', 'fri-web-2', 'fri-web-8', 'thu-web-8']
  },
  {
    id: 'php-get-post', language: 'PHP', category: 'Formulaire', type: 'Récupération de données',
    title: 'Lire GET ou POST en PHP', priority: 'frequent',
    description: 'Récupérer une valeur envoyée dans l’URL ou le corps d’un formulaire.',
    syntax: "$nom = $_GET['nom'] ?? '';\n$nom = $_POST['nom'] ?? '';",
    example: "<?php\n$recherche = trim($_GET['q'] ?? '');\n$nom = trim($_POST['nom'] ?? '');\necho htmlspecialchars($nom, ENT_QUOTES, 'UTF-8');\n?>",
    remember: ['GET sert aux paramètres de consultation partageables.', 'POST convient à l’envoi d’un formulaire ; protéger les données avec HTTPS.'],
    pitfalls: ['Valider les valeurs reçues.', 'Échapper le texte affiché pour limiter les XSS.'],
    exercise: 'Traiter GET pour une recherche et POST pour une inscription.', tags: ['php', 'get', 'post', '$_get', '$_post', 'formulaire'],
    examIds: ['tue-web-3', 'wed-web-5', 'thu-web-8', 'fri-web-2']
  },
  {
    id: 'php-form-process', language: 'PHP', category: 'Formulaire', type: 'Traitement de formulaire',
    title: 'Traiter un formulaire POST', priority: 'complementary',
    description: 'Vérifier la méthode, valider les champs, puis traiter les données côté serveur.',
    syntax: "if ($_SERVER['REQUEST_METHOD'] === 'POST') {\n  $valeur = trim($_POST['champ'] ?? '');\n  // valider puis traiter\n}",
    example: "<?php\n$erreur = '';\nif ($_SERVER['REQUEST_METHOD'] === 'POST') {\n  $nom = trim($_POST['nom'] ?? '');\n  if ($nom === '') {\n    $erreur = 'Le nom est obligatoire.';\n  } else {\n    // traiter la valeur validée\n  }\n}\n?>",
    remember: ['Le navigateur ne remplace pas la validation serveur.', 'Échapper toute donnée affichée dans du HTML.'],
    pitfalls: ['Une valeur absente déclenche un avertissement si l’on n’utilise pas ?? ou une vérification.'],
    exercise: 'Valider le formulaire d’inscription avant d’enregistrer un étudiant.', tags: ['php', 'post', 'traitement', 'validation', 'formulaire'],
    examIds: ['fri-web-8', 'thu-web-8']
  },
  {
    id: 'db-many-to-many', language: 'Autres', category: 'Base de données', type: 'Modélisation',
    title: 'Modéliser une relation plusieurs-à-plusieurs', priority: 'essential',
    description: 'Créer une table associative quand chaque côté peut être lié à plusieurs lignes de l’autre.',
    syntax: 'TABLE_A 1 —— 0..* ASSOCIATION 0..* —— 1 TABLE_B\nPK associative : (id_a, id_b)',
    example: 'ETUDIANT 1 —— 0..* INSCRIPTION 0..* —— 1 COURS\nINSCRIPTION(IdEtudiant FK, IdCours FK, DateInscription)\nPK(INSCRIPTION) = (IdEtudiant, IdCours)',
    remember: ['La table associative porte les deux clés étrangères.', 'Les attributs propres au lien vont dans la table associative.'],
    pitfalls: ['Ne pas représenter directement un plusieurs-à-plusieurs en relationnel sans table de liaison.'],
    exercise: 'Modéliser étudiants-cours, commandes-produits, ou passagers-trajets.', tags: ['base de données', 'association', 'relation', 'cardinalité', 'clé composée', 'uml'],
    examIds: ['special-monday-uml', 'special-tuesday-uml', 'silthu-uml-5', 'silwed-uml-5']
  },
  {
    id: 'db-relationship-keys', language: 'Autres', category: 'Base de données', type: 'Clés et relations',
    title: 'Repérer PK, FK et table mère/fille', priority: 'essential',
    description: 'Lire les identifiants et suivre le sens d’une relation entre tables.',
    syntax: 'PARENT(id PRIMARY KEY, ...)\nENFANT(id PRIMARY KEY, parent_id FOREIGN KEY REFERENCES PARENT(id))',
    example: 'CLIENT(IdClient PK, Nom, Prenom)\nCOMMANDE(IdCommande PK, DateCommande, IdClient FK)\nUne commande appartient à un client ; un client peut avoir plusieurs commandes.',
    remember: ['La FK se trouve dans la table enfant.', 'Une clé composée utilise plusieurs colonnes.', 'L’intégrité référentielle impose une référence existante.'],
    pitfalls: ['Une FK peut se répéter ; une PK identifie une ligne de façon unique.'],
    exercise: 'Identifier les clés dans les schémas étudiant/inscription, client/commande ou hôtel.', tags: ['base de données', 'pk', 'fk', 'clé primaire', 'clé étrangère', 'relation'],
    examIds: ['special-monday-sql', 'special-tuesday-sql', 'special-wednesday-sql', 'silwed-sql-1', 'silwed-sql-2', 'silthu-sql-2']
  },
  {
    id: 'net-subnet-hosts', language: 'Autres', category: 'Réseau', type: 'Calcul réseau',
    title: 'Calculer un sous-réseau CIDR', priority: 'essential',
    description: 'Déduire réseau, broadcast et plage d’hôtes à partir d’une IPv4 et d’un préfixe.',
    syntax: 'hôtes = 2^(32 - préfixe) - 2\ntaille du bloc = 2^(32 - préfixe)\nréseau = début du bloc ; broadcast = fin du bloc',
    example: '172.16.5.130/26\nMasque 255.255.255.192 ; bloc de 64\nRéseau .128 ; broadcast .191\nHôtes .129–.190 ; 62 hôtes',
    remember: ['Soustraire 2 pour réseau et broadcast dans un sous-réseau IPv4 classique.', 'Un /27 donne 30 hôtes ; /26 donne 62 ; /29 donne 6.'],
    pitfalls: ['Ne pas confondre nombre total d’adresses et hôtes utilisables.', 'Les blocs du dernier octet sont alignés sur la taille du bloc.'],
    exercise: 'Résoudre les applications /24, /27, /29 et plans VLSM des sujets.', tags: ['réseau', 'cidr', 'sous-réseau', 'masque', 'broadcast', 'vlsm', 'ip'],
    examIds: ['app1-2', 'app2-3', 'app3-4', 'subnet-4', 'tue-net-3', 'special-tuesday-network', 'special-wednesday-network', 'silthu-net-4', 'silwed-net-4']
  },
  {
    id: 'net-dhcp-dora', language: 'Autres', category: 'Réseau', type: 'Diagnostic réseau',
    title: 'Reconnaître une panne DHCP avec DORA', priority: 'frequent',
    description: 'Une IPv4 169.254.x.x indique souvent qu’aucun bail DHCP n’a été obtenu.',
    syntax: 'Discover → Offer → Request → Acknowledge\nVérifier : lien/VLAN → adresse et bail → serveur/relai DHCP',
    example: 'Windows : ipconfig /all\nRenouveler : ipconfig /release puis ipconfig /renew\nTester la passerelle : ping adresse_passerelle',
    remember: ['DHCP fournit adresse IP, masque, passerelle et DNS.', 'Serveur DHCP UDP 67 ; client UDP 68.'],
    pitfalls: ['169.254.x.x décrit un symptôme ; vérifier câble, VLAN, portée, serveur et relais.'],
    exercise: 'Diagnostiquer un poste sans adresse automatique dans un service ou un cybercafé.', tags: ['réseau', 'dhcp', 'dora', '169.254', 'ipconfig', 'diagnostic'],
    examIds: ['tue-net-5', 'fri-net-8', 'thu-net-2', 'thu-net-5', 'thu-net-6', 'special-tuesday-network', 'special-wednesday-network', 'silthu-net-5', 'silwed-net-3']
  },
  {
    id: 'net-connectivity', language: 'Autres', category: 'Réseau', type: 'Diagnostic réseau',
    title: 'Diagnostiquer une perte de connectivité', priority: 'frequent',
    description: 'Tester du lien physique jusqu’au DNS pour localiser la panne.',
    syntax: 'lien → ipconfig → ping passerelle → ping IP distante → nslookup nom',
    example: '1. Vérifier câble, Wi-Fi et voyants du switch.\n2. ipconfig /all\n3. ping passerelle\n4. ping 8.8.8.8\n5. nslookup exemple.com\n6. tracert exemple.com',
    remember: ['Si l’IP distante répond mais pas le nom, suspecter DNS.', 'Si la passerelle ne répond pas, vérifier adresse, masque, VLAN et lien.'],
    pitfalls: ['Un ping bloqué par pare-feu ne prouve pas toujours que le serveur est hors ligne.'],
    exercise: 'Suivre la démarche pas à pas dans les sujets spécialité réseau.', tags: ['réseau', 'ping', 'ipconfig', 'tracert', 'nslookup', 'dns', 'diagnostic'],
    examIds: ['fri-net-2', 'fri-net-4', 'silthu-net-5', 'silwed-net-5', 'special-monday-network', 'special-tuesday-network', 'special-wednesday-network']
  }
];
